// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PowerUsageCUI.DataModel.PowerModel;

#nullable disable

namespace PowerUsageCUI.Migrations
{
    [DbContext(typeof(PowerModelContext))]
    partial class PowerModelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("PowerUsageCUI.DataModel.PowerModel.ThreePhaseMeter", b =>
                {
                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .HasColumnType("TEXT");

                    b.Property<float>("ActivePowerPhase1")
                        .HasColumnType("REAL");

                    b.Property<float>("ActivePowerPhase2")
                        .HasColumnType("REAL");

                    b.Property<float>("ActivePowerPhase3")
                        .HasColumnType("REAL");

                    b.Property<float>("TotalActivePower")
                        .HasColumnType("REAL");

                    b.HasKey("DateTime", "DeviceName");

                    b.ToTable("ThreePhaseMeterSet");
                });
#pragma warning restore 612, 618
        }
    }
}
